name: Check benchmark of jsonparse

on: [push, pull_request]

jobs:
  benchmark-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install TeX Live
      uses: zauguin/install-texlive@v4
      with:
        package_file: .github/tl-packages.txt
    - name: Run benchmark check
      run: |
        pdflatex benchmark.tex
      working-directory: benchmark/
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add benchmark/README.md
        git add benchmark/benchmark.pdf
        git commit -m "Update benchmark results (Action)"
        git push
