name: Test jsonparse using l3build -dev

on: [push, pull_request]

jobs:
  l3build-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install TeX Live
      uses: zauguin/install-texlive@v3
      with:
        package_file: .github/tl-packages.txt
    - name: Run l3build check -dev
      run: |
        l3build check --dev -q -H --show-log-on-error